app: fp backend v1.0

database:
  name: back
  type: 1  # 1- sqlite 2- postgres
  host: db
  user: fiveplus
  password: ./secrets/db.password
  timezone: Europe/Moscow
  port: 5432
  sslmode: true

auth:
  audience:
    - "fpb >= v0.3"
    - "fpc >= v1.0"
  accessexpired: 1h
  refreshexpired: 30d
  changeexpires: 15m
  chatexpires: 4h
  refreshlength: 64
  keys:
    private: ./secrets/private.pem
    public: ./secrets/public.pem

handlers:
  emailconfirmationexpired: 30m

sender:
  email:
    sendertype: 1 # now only 1- strayt login
    email: ivannebotov@justnets.ru
    password: ./secrets/email.password
    smtpserver: smtp.yandex.com
    port: 465
    ssl: true
    verificationchangetemplate: ./templates/change_verification.html
    verificationemailtemplate: ./templates/email_verification.html
    deletechildtemplate: ./templates/delete_child_verification.html

chat:
  writewait: 10s # max wait time when writing message to peer
  pongwait: 1m # max time till next pong from peer
  maxmessagesize: 10000 # maximum message size allowed from peer.
