version: "3.5"

services:
  traefik:
    image: traefik:v2.2
    container_name: traefik
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${PWD}/traefik.toml:/traefik.toml"
      - "${PWD}/traefik_dynamic.toml:/traefik_dynamic.toml"
      - "${PWD}/acme.json:/acme.json "
    networks:
      - web

networks:
  web:
    external: true