[http.middlewares.PassiveAdmin.basicAuth]
users = [
    "admin:$apr1$IxqGR.c0$xSVq3XTYBRY/3M648EbU51"
]

[http.routers.api]
    rule = "Host(`traefik.justnets.ru`)"
    entrypoints = ["https"]
    middlewares = ["PassiveAdmin"]
    service = "api@internal"
[http.routers.api.tls]
    certResolver = "letsencrypt"